#  owner: rg

#  a function for calculating the mission revenue
def calculate_revenue(mission):
    #  mission is a Mission object with attribute
    #+ ntr, which is a SpaceCraft object
    
    #  the revenue generated by the mission is added as
    #+ an attribute to the mission
    mission.revenue = 1