#  owner: rg

#  a function for calculating the mission revenue
def calculate_revenue(parent):
    '''  mission is a Mission object with attribute
    #+ ntr, which is a SpaceCraft object

    #  the revenue generated by the mission is added as
    #+ an attribute to the mission

    Requires additions to the mission object:
        mission.launch_vehicle.mass_to_orbit
        mission.launch_vehicle.cost_per_mass
    '''
    import launchvehicle

    parent.revenue = 1
    total_used_mass = parent.payload.mass + parent.fuel.mass
    mass_to_orbit, cost = launchvehicle.mass_to_orbit(parent)
    free_mass = mass_to_orbit - total_used_mass
    cost_per_mass = cost/mass_to_orbit
    parent.revenue = free_mass/cost_per_mass
