#  owner: rg
from launchvehicle import mass_to_orbit

#  a function for calculating the mission revenue
def calculate_revenue(mission):
    '''  mission is a Mission object with attribute
    #+ ntr, which is a SpaceCraft object

    #  the revenue generated by the mission is added as
    #+ an attribute to the mission

    Requires additions to the mission object:
        mission.launch_vehicle.mass_to_orbit
        mission.launch_vehicle.cost_per_mass
    '''


    mission.revenue = 1
    total_used_mass = mission.payload.mass + mission.fuel.mass
    lv_mass_orbit_orbit = mass_to_orbit(mission)
    free_mass = lv_mass_orbit_orbit - total_used_mass
    mission.revenue = free_mass/mission.launch_vehicle.cost_per_mass

